name: Gonddo
markdown: kramdown
permalink: pretty
baseurl: /

# Assets
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

sass:
  sass_dir:          _scss
  style:            :compressed

# Analytics
google_analytics: "UA-140386190-1"

# FormSpree
sign_in_url: http://app.gonddo.com.br/public/request_invite
formspree_contact_url: https://formspree.io/bruno.passos@gonddo.com.br
